# Generated by Django 5.1.2 on 2024-10-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_alter_taxa_tipo_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxa',
            name='tipo_produto',
        ),
        migrations.AddField(
            model_name='taxa',
            name='tipos_produto',
            field=models.ManyToManyField(related_name='taxas', to='fornecedores.tipoproduto'),
        ),
    ]
