# Generated by Django 5.1.2 on 2024-10-31 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_camisetatamanho_estoque_minimo'),
        ('vendas', '0002_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='itens',
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.camiseta')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_compra', to='vendas.compra')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.camisetatamanho')),
            ],
        ),
    ]
