# Generated by Django 5.1.2 on 2024-10-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('temporada', models.CharField(max_length=50)),
                ('estilo', models.CharField(max_length=50)),
                ('cor_principal', models.CharField(max_length=50)),
                ('patrocinador', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='camisetas/')),
            ],
        ),
        migrations.CreateModel(
            name='CamisetaTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=2)),
                ('quantidade_em_estoque', models.IntegerField()),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='store.camiseta')),
            ],
        ),
    ]
