# Generated by Django 5.1.2 on 2024-10-10 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camiseta',
            old_name='preco',
            new_name='preco_custo',
        ),
        migrations.AddField(
            model_name='camiseta',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='tipo_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.tipoproduto'),
        ),
    ]
