# Generated by Django 5.1.2 on 2024-10-30 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_historicoestoque_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoestoque',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_estoque', to='store.camisetatamanho'),
        ),
    ]
