# Generated by Django 5.1.2 on 2024-10-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_historicoestoque_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoEstoque',
        ),
    ]
