# Generated by Django 5.1.2 on 2024-10-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_historicoestoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoestoque',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='historicoestoque',
            name='email_usuario',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicoestoque',
            name='estoque_anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoestoque',
            name='estoque_novo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicoestoque',
            name='tamanho',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
