# Generated by Django 5.1.3 on 2024-11-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_historicoestoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='liga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
