# Generated by Django 5.1.2 on 2024-11-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_liga_marca_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.marca'),
        ),
    ]
