# Generated by Django 5.1.2 on 2024-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_camiseta_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
