# Generated by Django 5.1.2 on 2024-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_camiseta_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
