# Generated by Django 5.1.2 on 2024-11-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_camiseta_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='liga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
